;VITOR AUGUSTO GON?ALVES REIS
    

#include "p16f628a.inc"

; CONFIG
; __config 0xFF70
__CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF


RES_VECT CODE 0x0000 ; VETOR DE RESET, INDICA A POSI??O INICIAL DO PROGRAMA NA FLASH
    BSF STATUS,RP0 ; SELECIONA O BANCO I DA MEMORIA RAM
    BCF TRISB,0 ; CONFIGURA O PINO 0 DA PORTA COMO SAIDA
    BCF TRISB,1 ; CONFIGURA O PINO 1 DA PORTA COMO SAIDA 
    BCF TRISB,2 ; CONFIGURA O PINO 2 DA PORTA COMO SAIDA
    BCF TRISB,3 ; CONFIGURA O PINO 3 DA PORTA COMO SAIDA
    BCF	TRISA,0 ; CONFIGURA O PINO A0 COMO SAIDA
    bcf STATUS,RP0 ; SELECIONA O BANCO 0 DA MEMORIA RAM
    BCF	PORTB,0 ; APAGA A LAMPADA
    BCF	PORTB,1 ; APAGA A LAMPADA
    BSF	PORTB,2 ; ACENDE A LAMPADA
    BCF	PORTB,3 ; APAGA LAMPADA
    BCF PORTA,0

DESLIGA
    BTFSC PORTA,3 ;LE E TESTA O BIT 0 DA PORTA
    GOTO EMERGENCIA
    BCF	PORTB,0 ; APAGA A LAMPADA
    BCF	PORTB,1 ; APAGA A LAMPADA
    BSF	PORTB,2 ; ACENDE A LAMPADA
    BCF	PORTB,3 ; APAGA LAMPADA
    BCF PORTA,0
    
EMERGENCIA
    BTFSC PORTA,4 ;LE E TESTA O BIT 0 DA PORTA
    GOTO HORARIO
    BCF	PORTB,0 ; APAGA A LAMPADA
    BCF	PORTB,1 ; APAGA A LAMPADA
    BSF	PORTB,2 ; APAGA A LAMPADA
    BSF	PORTB,3 ; ACENDE LAMPADA
    BCF PORTA,0

VERIFDESLIGA
    BTFSC PORTA,3
    GOTO  VERIFDESLIGA
    GOTO DESLIGA
    
    

    
HORARIO
    BTFSC PORTA,1 ;LE E TESTA O BIT 0 DA PORTA
    GOTO ANTIHORARIO
    BTFSC PORTA,0
    GOTO ANTIHORARIO
    BSF	PORTB,0 ; APAGA A LAMPADA
    BCF	PORTB,1 ; APAGA A LAMPADA
    BCF	PORTB,2 ; APAGA A LAMPADA
    BCF	PORTB,3 ; ACENDE LAMPADA
    BSF PORTA,0

ANTIHORARIO
    BTFSC PORTA,2
    GOTO  DESLIGA
    BTFSC PORTA,0
    GOTO  DESLIGA
    BCF	PORTB,0 ; APAGA A LAMPADA
    BSF	PORTB,1 ; APAGA A LAMPADA
    BCF	PORTB,2 ; APAGA A LAMPADA
    BCF	PORTB,3 ; ACENDE LAMPADA
    BSF PORTA,0
    GOTO DESLIGA
    


END
