;VITOR AUGUSTO GONÇALVES REIS

#include "p16f628a.inc"

; CONFIG
; __config 0xFF70
__CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF


RES_VECT CODE 0x0000 ; VETOR DE RESET, INDICA A POSIÇÃO INICIAL DO PROGRAMA NA FLASH
    BSF STATUS,RP0 ; SELECIONA O BANCO I DA MEMORIA RAM
    BCF TRISB,0 ; CONFIGURA O PINO 0 DA PORTA COMO SAIDA
    BCF TRISB,1 ; CONFIGURA O PINO 1 DA PORTA COMO SAIDA 
    BCF TRISB,2 ; CONFIGURA O PINO 2 DA PORTA COMO SAIDA
    BCF TRISB,3 ; CONFIGURA O PINO 3 DA PORTA COMO SAIDA
    bcf STATUS,RP0 ; SELECIONA O BANCO 0 DA MEMORIA RAM
    BCF	PORTB,0 ; APAGA A LAMPADA
    BCF	PORTB,1 ; APAGA A LAMPADA
    BCF	PORTB,2 ; APAGA A LAMPADA
    BCF	PORTB,3 ; APAGA LAMPADA

ETAPA0
    BTFSC PORTA,1 ;LE E TESTA O BIT 1 DA PORTA
    GOTO ETAPA0	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BSF	PORTB,0 ;SE FOI CLICADO ACENDE A LAMPADA
    
ETAPA1
    BTFSC PORTA,2 ;LE E TESTA O BIT 2 DA PORTA
    GOTO ETAPA1	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BSF	PORTB,1 ;SE FOI CLICADO ACENDE A LAMPADA
    
ETAPA2
    BTFSC PORTA,3 ;LE E TESTA O BIT 3 DA PORTA
    GOTO ETAPA2	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BSF	PORTB,2 ;SE FOI CLICADO ACENDE A LAMPADA
    
ETAPA3
    BTFSC PORTA,4 ;LE E TESTA O BIT 4 DA PORTA
    GOTO ETAPA3	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BSF	PORTB,3 ;SE FOI CLICADO ACENDE A LAMPADA
    
ETAPA4
    BTFSC PORTA,1 ;LE E TESTA O BIT 1 DA PORTA
    GOTO ETAPA4	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BCF	PORTB,0 ;SE FOI CLICADO APAGA A LAMPADA
    
ETAPA5
    BTFSC PORTA,2 ;LE E TESTA O BIT 2 DA PORTA
    GOTO ETAPA5	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BCF	PORTB,1 ;SE FOI CLICADO APAGA A LAMPADA
    
ETAPA6
    BTFSC PORTA,3 ;LE E TESTA O BIT 3 DA PORTA
    GOTO ETAPA6	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BCF	PORTB,2 ;SE FOI CLICADO APAGA A LAMPADA
    
ETAPA7
    BTFSC PORTA,4 ;LE E TESTA O BIT 1 DA PORTA
    GOTO ETAPA7	;SE O BOTAO FOI NÃO FOI CLICADO OLHA DE NOVO
    BCF	PORTB,3 ;SE FOI CLICADO APAGA A LAMPADA
    GOTO ETAPA0
    

END

